### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by douyw** [thiennq/node-gtts#1]
Hi, thank you for this package. It's just what I want. I copy&pasted the sample code (i-love-you) in the README into index.js file, but it runs with error outputs. What's wrong with my development environment? How to fix it? 

```
~/tts/node-gtts$ pwd
/home/derek/tts/node-gtts

~/tts/node-gtts$ ls
index.js  node_modules

~/tts/node-gtts$ nodejs --version
v4.2.6

~/tts/node-gtts$ nodejs index.js
/home/derek/tts/node-gtts/node_modules/node-gtts/index.js:155
  for (let p of parts) {
       ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/derek/tts/node-gtts/index.js:1:74)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

**Comment by douyw** [comment]
I fixed it. Just add "use strict"; at the very beginning of that reported file - /home/derek/tts/node-gtts/node_modules/node-gtts/index.js.
